# Станции из https://gist.github.com/ergoz/e7837a54956116167db93b016dbd51a9
# (основные таблицы + каналы Radio Record из комментариев + Retrowave/SPB1).
# 2026-08-06: dead streams removed after prod probe — see context/radio_catalog_cleanup_2026-08-06.md
GIST_STATIONS = [
    {"name": "Радио Мелодия (СПБ)", "stream_url": "http://stream128.melodiafm.spb.ru:8000/melodia128", "genre": "Ретро"},
    {"name": "French Jazz", "stream_url": "http://icepe6.infomaniak.ch:80/jazz-wr01-128.mp3", "genre": "Jazz, Retro"},
    {"name": "Радио Маяк", "stream_url": "https://icecast-vgtrk.cdnvideo.ru/mayakfm_aac_64kbps", "genre": "News, Talk"},
    {"name": "Радио Ретро Хит", "stream_url": "http://air.volna.top/Retro", "genre": "Ретро"},
    {"name": "Fallout FM", "stream_url": "http://fallout.fm:8000/falloutfm1.ogg", "genre": "Game, Ambient"},
    {"name": "Jazz FM 89.1", "stream_url": "http://nashe1.hostingradio.ru/jazz-128.mp3", "genre": "Jazz"},
    {"name": "Christmas Radio", "stream_url": "http://relay4.181.fm:8124", "genre": "Christmas, Holiday"},
    {"name": "Хайп ФМ", "stream_url": "http://air.volna.top/HypeFM", "genre": "Pop, Hits"},
    {"name": "Discover Trance", "stream_url": "http://paris.discovertrance.com:8006/;stream.nsv", "genre": "Trance, Electronic"},
    {"name": "90's Eurodance", "stream_url": "http://listen1.myradio24.com:9000/5967", "genre": "90s, Eurodance"},
    {"name": "РетроФМ", "stream_url": "http://hls-01-retro.emgsound.ru/12/128/playlist.m3u8", "genre": "Ретро"},
    {"name": "Русское Радио", "stream_url": "https://rusradio.hostingradio.ru/rusradio128.mp3", "genre": "Pop, Russian"},
    {"name": "Вести ФМ", "stream_url": "http://icecast.vgtrk.cdnvideo.ru/vestifm_mp3_128kbps", "genre": "News"},
    {"name": "RADIO SPB1 Trance", "stream_url": "https://myradio24.org/2666", "genre": "Trance", "website": "https://radio-spb1.ru"},
    {"name": "Radio Record", "stream_url": "https://radiorecord.hostingradio.ru/rr_main96.aacp", "genre": "Dance, EDM", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Russian Mix", "stream_url": "https://radiorecord.hostingradio.ru/rus96.aacp", "genre": "Dance, Russian", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Summer Dance", "stream_url": "https://radiorecord.hostingradio.ru/summerparty96.aacp", "genre": "Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Супердискотека 90-х", "stream_url": "https://radiorecord.hostingradio.ru/sd9096.aacp", "genre": "90s, Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Deep", "stream_url": "https://radiorecord.hostingradio.ru/deep96.aacp", "genre": "Deep House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Chill-Out", "stream_url": "https://radiorecord.hostingradio.ru/chil96.aacp", "genre": "Chill", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — На шашлыки!", "stream_url": "https://radiorecord.hostingradio.ru/nashashlyki96.aacp", "genre": "Pop", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Megamix", "stream_url": "https://radiorecord.hostingradio.ru/mix96.aacp", "genre": "Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Rock", "stream_url": "https://radiorecord.hostingradio.ru/rock96.aacp", "genre": "Rock", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Remix", "stream_url": "https://radiorecord.hostingradio.ru/rmx96.aacp", "genre": "Remix, Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Гоп FM", "stream_url": "https://radiorecord.hostingradio.ru/gop96.aacp", "genre": "Rap, Russian", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Chill House", "stream_url": "https://radiorecord.hostingradio.ru/chillhouse96.aacp", "genre": "House, Chill", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Big Hits", "stream_url": "https://radiorecord.hostingradio.ru/bighits96.aacp", "genre": "Hits", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Рекорд 00-х", "stream_url": "https://radiorecord.hostingradio.ru/200096.aacp", "genre": "00s", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Record 80-х", "stream_url": "https://radiorecord.hostingradio.ru/198096.aacp", "genre": "80s", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Нафталин FM", "stream_url": "https://radiorecord.hostingradio.ru/naft96.aacp", "genre": "Oldies", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Маятник Фуко", "stream_url": "https://radiorecord.hostingradio.ru/mf96.aacp", "genre": "Electronic", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Trancemission", "stream_url": "https://radiorecord.hostingradio.ru/tm96.aacp", "genre": "Trance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Russian Gold", "stream_url": "https://radiorecord.hostingradio.ru/russiangold96.aacp", "genre": "Russian", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Pirate Station", "stream_url": "https://radiorecord.hostingradio.ru/ps96.aacp", "genre": "Drum & Bass", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Innocence", "stream_url": "https://radiorecord.hostingradio.ru/ibiza96.aacp", "genre": "House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Медляк FM", "stream_url": "https://radiorecord.hostingradio.ru/mdl96.aacp", "genre": "Slow, Pop", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Party 24/7", "stream_url": "https://radiorecord.hostingradio.ru/party96.aacp", "genre": "Party, Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Phonk", "stream_url": "https://radiorecord.hostingradio.ru/phonk96.aacp", "genre": "Phonk", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Record Gold", "stream_url": "https://radiorecord.hostingradio.ru/gold96.aacp", "genre": "Hits", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Руки Вверх!", "stream_url": "https://radiorecord.hostingradio.ru/rv96.aacp", "genre": "Pop, Russian", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — На Хайпе", "stream_url": "https://radiorecord.hostingradio.ru/hype96.aacp", "genre": "Hits", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Rap Hits", "stream_url": "https://radiorecord.hostingradio.ru/rap96.aacp", "genre": "Rap", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Rap Classics", "stream_url": "https://radiorecord.hostingradio.ru/rapclassics96.aacp", "genre": "Rap", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Trance Classics", "stream_url": "https://radiorecord.hostingradio.ru/trancehits96.aacp", "genre": "Trance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Колбасный Цех", "stream_url": "https://radiorecord.hostingradio.ru/pump96.aacp", "genre": "Hard Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — D'n'B Classics", "stream_url": "https://radiorecord.hostingradio.ru/drumhits96.aacp", "genre": "Drum & Bass", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Armin van Buuren", "stream_url": "https://radiorecord.hostingradio.ru/armin96.aacp", "genre": "Trance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Organic", "stream_url": "https://radiorecord.hostingradio.ru/organic96.aacp", "genre": "Organic House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — VIP House", "stream_url": "https://radiorecord.hostingradio.ru/vip96.aacp", "genre": "House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Breaks", "stream_url": "https://radiorecord.hostingradio.ru/brks96.aacp", "genre": "Breaks", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Liquid Funk", "stream_url": "https://radiorecord.hostingradio.ru/liquidfunk96.aacp", "genre": "Drum & Bass", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Workout", "stream_url": "https://radiorecord.hostingradio.ru/workout96.aacp", "genre": "Workout", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — EDM", "stream_url": "https://radiorecord.hostingradio.ru/club96.aacp", "genre": "EDM", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Bass House", "stream_url": "https://radiorecord.hostingradio.ru/jackin96.aacp", "genre": "Bass House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — GOA/PSY", "stream_url": "https://radiorecord.hostingradio.ru/goa96.aacp", "genre": "Psytrance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — 10's Dance", "stream_url": "https://radiorecord.hostingradio.ru/201096.aacp", "genre": "10s, Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Trancehouse", "stream_url": "https://radiorecord.hostingradio.ru/trancehouse96.aacp", "genre": "Trance, House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Black Rap", "stream_url": "https://radiorecord.hostingradio.ru/yo96.aacp", "genre": "Rap", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Techno", "stream_url": "https://radiorecord.hostingradio.ru/techno96.aacp", "genre": "Techno", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Tropical", "stream_url": "https://radiorecord.hostingradio.ru/trop96.aacp", "genre": "Tropical", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Lo-Fi", "stream_url": "https://radiorecord.hostingradio.ru/lofi96.aacp", "genre": "Lo-Fi", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Tech House", "stream_url": "https://radiorecord.hostingradio.ru/techouse96.aacp", "genre": "Tech House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Trap", "stream_url": "https://radiorecord.hostingradio.ru/trap96.aacp", "genre": "Trap", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Technopop", "stream_url": "https://radiorecord.hostingradio.ru/technopop96.aacp", "genre": "Technopop", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — 70's Dance", "stream_url": "https://radiorecord.hostingradio.ru/197096.aacp", "genre": "70s, Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Dream Dance", "stream_url": "https://radiorecord.hostingradio.ru/dream96.aacp", "genre": "Dream Dance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Neurofunk", "stream_url": "https://radiorecord.hostingradio.ru/neurofunk96.aacp", "genre": "Neurofunk", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Ambient", "stream_url": "https://radiorecord.hostingradio.ru/ambient96.aacp", "genre": "Ambient", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Eurodance", "stream_url": "https://radiorecord.hostingradio.ru/eurodance96.aacp", "genre": "Eurodance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — House Hits", "stream_url": "https://radiorecord.hostingradio.ru/househits96.aacp", "genre": "House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Uplifting", "stream_url": "https://radiorecord.hostingradio.ru/uplift96.aacp", "genre": "Trance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Tiesto", "stream_url": "https://radiorecord.hostingradio.ru/tiesto96.aacp", "genre": "EDM", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Веснушка FM", "stream_url": "https://radiorecord.hostingradio.ru/deti96.aacp", "genre": "Kids", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Симфония FM", "stream_url": "https://radiorecord.hostingradio.ru/symph96.aacp", "genre": "Classical", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Minimal/Tech", "stream_url": "https://radiorecord.hostingradio.ru/mini96.aacp", "genre": "Minimal, Techno", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — TOP 100 EDM", "stream_url": "https://radiorecord.hostingradio.ru/top100edm96.aacp", "genre": "EDM", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Dream Pop", "stream_url": "https://radiorecord.hostingradio.ru/dreampop96.aacp", "genre": "Dream Pop", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — House Classics", "stream_url": "https://radiorecord.hostingradio.ru/houseclss96.aacp", "genre": "House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — David Guetta", "stream_url": "https://radiorecord.hostingradio.ru/guetta96.aacp", "genre": "EDM", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Disco/Funk", "stream_url": "https://radiorecord.hostingradio.ru/discofunk96.aacp", "genre": "Disco, Funk", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Hard Bass", "stream_url": "https://radiorecord.hostingradio.ru/hbass96.aacp", "genre": "Hard Bass", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Rave FM", "stream_url": "https://radiorecord.hostingradio.ru/rave96.aacp", "genre": "Rave", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — 60's Dance", "stream_url": "https://radiorecord.hostingradio.ru/cadillac96.aacp", "genre": "60s", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Dancecore", "stream_url": "https://radiorecord.hostingradio.ru/dc96.aacp", "genre": "Dancecore", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Future House", "stream_url": "https://radiorecord.hostingradio.ru/fut96.aacp", "genre": "Future House", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Darkside", "stream_url": "https://radiorecord.hostingradio.ru/darkside96.aacp", "genre": "Dark", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Future Rave", "stream_url": "https://radiorecord.hostingradio.ru/futurerave96.aacp", "genre": "Rave", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Reggae", "stream_url": "https://radiorecord.hostingradio.ru/reggae96.aacp", "genre": "Reggae", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Electro", "stream_url": "https://radiorecord.hostingradio.ru/elect96.aacp", "genre": "Electro", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Hardstyle", "stream_url": "https://radiorecord.hostingradio.ru/teo96.aacp", "genre": "Hardstyle", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Dubstep", "stream_url": "https://radiorecord.hostingradio.ru/dub96.aacp", "genre": "Dubstep", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Progressive", "stream_url": "https://radiorecord.hostingradio.ru/progr96.aacp", "genre": "Progressive", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Synthwave", "stream_url": "https://radiorecord.hostingradio.ru/synth96.aacp", "genre": "Synthwave", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Latina Dance", "stream_url": "https://radiorecord.hostingradio.ru/latina96.aacp", "genre": "Latin", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — EDM Classics", "stream_url": "https://radiorecord.hostingradio.ru/edmhits96.aacp", "genre": "EDM", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Tecktonik", "stream_url": "https://radiorecord.hostingradio.ru/tecktonik96.aacp", "genre": "Tecktonik", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Jungle", "stream_url": "https://radiorecord.hostingradio.ru/jungle96.aacp", "genre": "Jungle", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Hypnotic", "stream_url": "https://radiorecord.hostingradio.ru/hypno96.aacp", "genre": "Trance", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — UK Garage", "stream_url": "https://radiorecord.hostingradio.ru/ukgarage96.aacp", "genre": "UK Garage", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Гастарбайтер FM", "stream_url": "https://radiorecord.hostingradio.ru/gast96.aacp", "genre": "Pop", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Midtempo", "stream_url": "https://radiorecord.hostingradio.ru/mt96.aacp", "genre": "Midtempo", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Future Bass", "stream_url": "https://radiorecord.hostingradio.ru/fbass96.aacp", "genre": "Future Bass", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Live DJ-sets", "stream_url": "https://radiorecord.hostingradio.ru/livedjsets96.aacp", "genre": "DJ Sets", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Русская Зима", "stream_url": "https://radiorecord.hostingradio.ru/ruszima96.aacp", "genre": "Russian", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Moombahton", "stream_url": "https://radiorecord.hostingradio.ru/mmbt96.aacp", "genre": "Moombahton", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — 2-step", "stream_url": "https://radiorecord.hostingradio.ru/2step96.aacp", "genre": "2-step", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Complextro", "stream_url": "https://radiorecord.hostingradio.ru/complextro96.aacp", "genre": "Complextro", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Groove/Tribal", "stream_url": "https://radiorecord.hostingradio.ru/groovetribal96.aacp", "genre": "Groove", "website": "https://www.radiorecord.ru/"},
    {"name": "Radio Record — Christmas Chill", "stream_url": "https://radiorecord.hostingradio.ru/christmaschill96.aacp", "genre": "Christmas, Chill", "website": "https://www.radiorecord.ru/"},
]
